# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  deploy:
     machine:
         enabled: true
     working_directory: ~/circleci-demo-workflows
     steps:
      - checkout
      - run:
         name: Moven install
         command: mvn install
      - run:
         name: Docker build 
         command: docker build -t 463442625423.dkr.ecr.us-east-2.amazonaws.com/yello-team-client-mgmt-repo:$CIRCLE_SHA1 .
      - run:
         name: Docker build latest
         command: docker build -t 463442625423.dkr.ecr.us-east-2.amazonaws.com/yello-team-client-mgmt-repo:latest .
      - run:
         name: Docker run
         command: docker run -d -p 8081:8081 --name yello-team 463442625423.dkr.ecr.us-east-2.amazonaws.com/yello-team-client-mgmt-repo:$CIRCLE_SHA1; sleep 10
      - run:  
         name: Change script permissions
         command: chmod +x ./deploy.sh
      - run:
         name: Deply script
         command: ./deploy.sh
     

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy